apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-processor
  labels:
    app: video-processor
spec:
  selector:
    matchLabels:
      app: video-processor
  template:
    metadata:
      labels:
        app: video-processor
    spec:
      containers:
        - name: video-processor
          image: cristianobarros/video-processor
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
          envFrom:
            - configMapRef:
                name: video-processor
            - secretRef:
                name: video-processor
          startupProbe:
            httpGet:
              port: http
              path: /actuator/health
            failureThreshold: 30
          readinessProbe:
            httpGet:
              port: http
              path: /actuator/health
          livenessProbe:
            httpGet:
              port: http
              path: /actuator/health
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi
