apiVersion: v1
kind: Secret
metadata:
  name: video-processor
type: Opaque
data:
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  AWS_REGION: ${AWS_REGION}
  SPRING_RABBITMQ_ADDRESSES: ${SPRING_RABBITMQ_ADDRESSES}
  SPRING_RABBITMQ_USERNAME: ${SPRING_RABBITMQ_USERNAME}
  SPRING_RABBITMQ_PASSWORD: ${SPRING_RABBITMQ_PASSWORD}
